export const RECRUITER_SCENE_PLATFORM_OUTER_TOP_RADIUS = 3.85;
export const RECRUITER_SCENE_PLATFORM_OUTER_BOTTOM_RADIUS = 4.22;
export const RECRUITER_SCENE_PLATFORM_HEIGHT = 0.12;
export const RECRUITER_SCENE_PLATFORM_RING_INNER_RADIUS = 3.36;
export const RECRUITER_SCENE_PLATFORM_RING_OUTER_RADIUS = 3.68;
export const RECRUITER_SCENE_PLATFORM_GLOW_RADIUS = 3.56;
