import type { WorkbenchDefinition, WorkbenchDistrictDefinition } from '../../src/types/workbench';

export const WORKBENCH_DISTRICTS: WorkbenchDistrictDefinition[] = [
  {
    id: 'work-experience',
    label: 'Work Experience District',
    corridors: ['southeast-trail', 'southern-link'],
    paletteDirection: 'Brushed metal, ember highlights, and disciplined workstation silhouettes.',
    defaultSpacing: 9.5,
    preferredLateralSide: 'right',
    decorativeRules: ['lanterns', 'utility-crates'],
  },
  {
    id: 'projects',
    label: 'Projects District',
    corridors: ['east-promenade', 'northern-link'],
    paletteDirection: 'Bright prototype colors, exposed parts, and inventive tabletop clutter.',
    defaultSpacing: 8.5,
    preferredLateralSide: 'right',
    decorativeRules: ['planters', 'utility-crates'],
  },
  {
    id: 'personal-life',
    label: 'Personal Life District',
    corridors: ['north-rise'],
    paletteDirection: 'Soft rose light, keepsakes, journals, and reflective materials.',
    defaultSpacing: 10,
    preferredLateralSide: 'left',
    decorativeRules: ['planters', 'stone-markers'],
  },
  {
    id: 'clubs',
    label: 'Clubs District',
    corridors: ['west-ridge', 'northern-link'],
    paletteDirection: 'Collaborative tables, banners, green accents, and communal props.',
    defaultSpacing: 8.75,
    preferredLateralSide: 'left',
    decorativeRules: ['flag-lines', 'planters'],
  },
  {
    id: 'extracurriculars',
    label: 'Extracurriculars District',
    corridors: ['southwest-trail', 'southern-link'],
    paletteDirection: 'Active cobalt accents, route markers, and field-ready equipment.',
    defaultSpacing: 9,
    preferredLateralSide: 'left',
    decorativeRules: ['stone-markers', 'lanterns'],
  },
];

export const WORKBENCH_LAYOUT: WorkbenchDefinition[] = [
  {
    id: 'work-experience-placeholder',
    title: 'Work Experience Placeholder',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'draft',
    contentMode: 'placeholder',
    placement: {
      mode: 'corridor',
      corridorId: 'southeast-trail',
      distanceAlong: 24,
      lateralOffset: 2.8,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.4,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'work-ember',
      accentMaterial: 'brushed-metal',
      propKit: 'software-station',
      heroProp: 'monitor-stack',
      animationStyle: 'signal-blink',
    },
    draftNotes: 'Reserve this corridor for core professional milestones like internships or full-time engineering roles.',
  },
  {
    id: 'projects-placeholder',
    title: 'Projects Placeholder',
    category: 'projects',
    district: 'projects',
    visibility: 'draft',
    contentMode: 'placeholder',
    placement: {
      mode: 'corridor',
      corridorId: 'east-promenade',
      distanceAlong: 19,
      lateralOffset: 2.3,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'atelier-worktable',
      palette: 'project-citrine',
      accentMaterial: 'powder-coat',
      propKit: 'prototype-lab',
      heroProp: 'signal-dish',
      animationStyle: 'soft-orbit',
    },
    draftNotes: 'Use for standout shipped or experimental personal projects that deserve their own sculptural prop story.',
  },
  {
    id: 'personal-life-placeholder',
    title: 'Personal Life Placeholder',
    category: 'personal-life',
    district: 'personal-life',
    visibility: 'draft',
    contentMode: 'placeholder',
    placement: {
      mode: 'corridor',
      corridorId: 'north-rise',
      distanceAlong: 21,
      lateralOffset: -2.5,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'journal-console',
      palette: 'personal-rose',
      accentMaterial: 'ceramic',
      propKit: 'reflection-nook',
      heroProp: 'memory-orb',
      animationStyle: 'paper-breeze',
    },
    draftNotes: 'Use for benches that share values, family, culture, travel, or personal insight through quieter objects.',
  },
  {
    id: 'clubs-placeholder',
    title: 'Clubs Placeholder',
    category: 'clubs',
    district: 'clubs',
    visibility: 'draft',
    contentMode: 'placeholder',
    placement: {
      mode: 'corridor',
      corridorId: 'west-ridge',
      distanceAlong: 17,
      lateralOffset: -2.7,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'commons-table',
      palette: 'club-verde',
      accentMaterial: 'warm-wood',
      propKit: 'club-circle',
      heroProp: 'club-banner',
      animationStyle: 'idle-pulse',
    },
    draftNotes: 'Hold collaborative student groups, org leadership, and communities that are best represented as shared tables.',
  },
  {
    id: 'extracurriculars-placeholder',
    title: 'Extracurriculars Placeholder',
    category: 'extracurriculars',
    district: 'extracurriculars',
    visibility: 'draft',
    contentMode: 'placeholder',
    placement: {
      mode: 'corridor',
      corridorId: 'southwest-trail',
      distanceAlong: 17,
      lateralOffset: -2.6,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'field-station',
      palette: 'extra-cobalt',
      accentMaterial: 'frosted-glass',
      propKit: 'field-kit',
      heroProp: 'wayfinder-arch',
      animationStyle: 'soft-orbit',
    },
    draftNotes: 'Use for sports, leadership, volunteering, and high-energy milestones that should feel directional and active.',
  },
];
