import type { WorkbenchDefinition, WorkbenchDistrictDefinition } from '../../src/types/workbench';

import { applyPublishedWorkbenchRingLayout, getPublishedWorkbenchClearZones } from '../../src/workbench/publishedRing';

export const WORKBENCH_DISTRICTS: WorkbenchDistrictDefinition[] = [
  {
    id: 'work-experience',
    label: 'Work Experience District',
    corridors: ['southeast-trail', 'southern-link', 'west-ridge'],
    paletteDirection: 'Structured workstations, control lights, and grounded career-story silhouettes.',
    defaultSpacing: 3.4,
    preferredLateralSide: 'right',
    decorativeRules: ['lanterns', 'utility-crates'],
  },
  {
    id: 'projects',
    label: 'Projects District',
    corridors: ['east-promenade', 'southeast-trail', 'southern-link'],
    paletteDirection: 'Prototype-forward stations, animated displays, and compact product vignettes.',
    defaultSpacing: 3.5,
    preferredLateralSide: 'right',
    decorativeRules: ['planters', 'utility-crates'],
  },
  {
    id: 'personal-life',
    label: 'Personal Life District',
    corridors: ['north-rise'],
    paletteDirection: 'Soft rose light, keepsakes, journals, and reflective materials.',
    defaultSpacing: 10,
    preferredLateralSide: 'left',
    decorativeRules: ['planters', 'stone-markers'],
  },
  {
    id: 'clubs',
    label: 'Clubs District',
    corridors: ['west-ridge', 'northern-link'],
    paletteDirection: 'Collaborative tables, banners, green accents, and communal props.',
    defaultSpacing: 8.75,
    preferredLateralSide: 'left',
    decorativeRules: ['flag-lines', 'planters'],
  },
  {
    id: 'extracurriculars',
    label: 'Extracurriculars District',
    corridors: ['southwest-trail', 'southern-link'],
    paletteDirection: 'Active cobalt accents, route markers, and field-ready equipment.',
    defaultSpacing: 9,
    preferredLateralSide: 'left',
    decorativeRules: ['stone-markers', 'lanterns'],
  },
];

const RAW_WORKBENCH_LAYOUT: WorkbenchDefinition[] = [
  {
    id: 'ssec-technical-computing',
    title: 'Technical Computing at SSEC',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'ssec-technical-computing',
    placement: {
      mode: 'freeform',
      x: -6.8,
      z: -10.2,
      rotationY: 0.588,
      yOffset: 0.18,
    },
    interactionRadius: 4.6,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'work-ember',
      accentMaterial: 'brushed-metal',
      propKit: 'software-station',
      heroProp: 'monitor-stack',
      animationStyle: 'signal-blink',
    },
  },
  {
    id: 'phoenix-aid-qa',
    title: 'Phoenix Aid at Accura Trials',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'phoenix-aid-qa',
    placement: {
      mode: 'freeform',
      x: -10.4,
      z: -8.8,
      rotationY: 0.869,
      yOffset: 0.18,
    },
    interactionRadius: 4.3,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'work-ember',
      accentMaterial: 'powder-coat',
      propKit: 'software-station',
      heroProp: 'signal-dish',
      animationStyle: 'signal-blink',
    },
  },
  {
    id: 'wisconsin-dnr-data-entry',
    title: 'Wisconsin DNR Data Entry',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'wisconsin-dnr-data-entry',
    placement: {
      mode: 'freeform',
      x: -13.4,
      z: -6.2,
      rotationY: 1.137,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'journal-console',
      palette: 'work-ember',
      accentMaterial: 'ceramic',
      propKit: 'software-station',
      heroProp: 'memory-orb',
      animationStyle: 'idle-pulse',
    },
  },
  {
    id: 'hlr-engineering-data',
    title: 'HLR Engineering',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'hlr-engineering-data',
    placement: {
      mode: 'freeform',
      x: -12.2,
      z: -2.9,
      rotationY: 1.337,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'atelier-worktable',
      palette: 'work-ember',
      accentMaterial: 'warm-wood',
      propKit: 'prototype-lab',
      heroProp: 'signal-dish',
      animationStyle: 'soft-orbit',
    },
  },
  {
    id: 'mathnasium-lead-instructor',
    title: 'Mathnasium Lead Instructor',
    category: 'work-experience',
    district: 'work-experience',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'mathnasium-lead-instructor',
    placement: {
      mode: 'freeform',
      x: -14.6,
      z: 0.6,
      rotationY: 1.612,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'commons-table',
      palette: 'work-ember',
      accentMaterial: 'warm-wood',
      propKit: 'club-circle',
      heroProp: 'club-banner',
      animationStyle: 'idle-pulse',
    },
  },
  {
    id: 'fridgefinder',
    title: 'FridgeFinder',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'fridgefinder',
    placement: {
      mode: 'freeform',
      x: 6.8,
      z: -10.2,
      rotationY: -0.588,
      yOffset: 0.18,
    },
    interactionRadius: 4.4,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'atelier-worktable',
      palette: 'project-citrine',
      accentMaterial: 'powder-coat',
      propKit: 'prototype-lab',
      heroProp: 'signal-dish',
      animationStyle: 'soft-orbit',
    },
  },
  {
    id: 'quant-signal-workstation',
    title: 'Quant Signal Workstation',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'quant-signal-workstation',
    placement: {
      mode: 'freeform',
      x: 10.5,
      z: -9,
      rotationY: -0.862,
      yOffset: 0.18,
    },
    interactionRadius: 4.4,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'project-citrine',
      accentMaterial: 'brushed-metal',
      propKit: 'software-station',
      heroProp: 'monitor-stack',
      animationStyle: 'signal-blink',
    },
  },
  {
    id: 'llm-research-agent',
    title: 'LLM Research Agent',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'llm-research-agent',
    placement: {
      mode: 'freeform',
      x: 13.4,
      z: -6.4,
      rotationY: -1.125,
      yOffset: 0.18,
    },
    interactionRadius: 4.4,
    priorityTier: 'anchor',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'project-citrine',
      accentMaterial: 'frosted-glass',
      propKit: 'software-station',
      heroProp: 'memory-orb',
      animationStyle: 'soft-orbit',
    },
  },
  {
    id: 'finance-ops-reconciliation',
    title: 'Finance Ops Reconciliation',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'finance-ops-reconciliation',
    placement: {
      mode: 'freeform',
      x: 11.2,
      z: -3.2,
      rotationY: -1.292,
      yOffset: 0.18,
    },
    interactionRadius: 4.1,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'console-desk',
      palette: 'project-citrine',
      accentMaterial: 'brushed-metal',
      propKit: 'software-station',
      heroProp: 'monitor-stack',
      animationStyle: 'signal-blink',
    },
  },
  {
    id: 'prediction-signal-ingestion-pipeline',
    title: 'Prediction Signal Ingestion Pipeline',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'prediction-signal-ingestion-pipeline',
    placement: {
      mode: 'freeform',
      x: 13.8,
      z: -0.2,
      rotationY: -1.556,
      yOffset: 0.18,
    },
    interactionRadius: 4.1,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'field-station',
      palette: 'project-citrine',
      accentMaterial: 'brushed-metal',
      propKit: 'field-kit',
      heroProp: 'signal-dish',
      animationStyle: 'signal-blink',
    },
  },
  {
    id: 'intellisort',
    title: 'IntelliSort',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'intellisort',
    placement: {
      mode: 'freeform',
      x: 13.2,
      z: 3.8,
      rotationY: -1.851,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'commons-table',
      palette: 'project-citrine',
      accentMaterial: 'powder-coat',
      propKit: 'prototype-lab',
      heroProp: 'signal-dish',
      animationStyle: 'idle-pulse',
    },
  },
  {
    id: 'footymind',
    title: 'FootyMind',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'footymind',
    placement: {
      mode: 'freeform',
      x: 10.4,
      z: 6.8,
      rotationY: -2.15,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'commons-table',
      palette: 'project-citrine',
      accentMaterial: 'frosted-glass',
      propKit: 'prototype-lab',
      heroProp: 'wayfinder-arch',
      animationStyle: 'soft-orbit',
    },
  },
  {
    id: 'elgin-help-hub',
    title: 'Elgin Help Hub',
    category: 'projects',
    district: 'projects',
    visibility: 'published',
    contentMode: 'linked',
    presentationMode: 'scene-owned',
    experienceId: 'elgin-help-hub',
    placement: {
      mode: 'freeform',
      x: 6.8,
      z: 8.6,
      rotationY: -2.473,
      yOffset: 0.18,
    },
    interactionRadius: 4,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'field-station',
      palette: 'project-citrine',
      accentMaterial: 'warm-wood',
      propKit: 'field-kit',
      heroProp: 'wayfinder-arch',
      animationStyle: 'idle-pulse',
    },
  },
  {
    id: 'personal-life-placeholder',
    title: 'Personal Life Placeholder',
    category: 'personal-life',
    district: 'personal-life',
    visibility: 'draft',
    contentMode: 'placeholder',
    presentationMode: 'scene-owned',
    placement: {
      mode: 'corridor',
      corridorId: 'north-rise',
      distanceAlong: 21,
      lateralOffset: -2.5,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'journal-console',
      palette: 'personal-rose',
      accentMaterial: 'ceramic',
      propKit: 'reflection-nook',
      heroProp: 'memory-orb',
      animationStyle: 'paper-breeze',
    },
    draftNotes: 'Reserved for personal-life benches after the recruiter MVP ships.',
  },
  {
    id: 'clubs-placeholder',
    title: 'Clubs Placeholder',
    category: 'clubs',
    district: 'clubs',
    visibility: 'draft',
    contentMode: 'placeholder',
    presentationMode: 'scene-owned',
    placement: {
      mode: 'corridor',
      corridorId: 'west-ridge',
      distanceAlong: 17,
      lateralOffset: -2.7,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'commons-table',
      palette: 'club-verde',
      accentMaterial: 'warm-wood',
      propKit: 'club-circle',
      heroProp: 'club-banner',
      animationStyle: 'idle-pulse',
    },
    draftNotes: 'Reserved for club and leadership benches after the recruiter MVP ships.',
  },
  {
    id: 'extracurriculars-placeholder',
    title: 'Extracurriculars Placeholder',
    category: 'extracurriculars',
    district: 'extracurriculars',
    visibility: 'draft',
    contentMode: 'placeholder',
    presentationMode: 'scene-owned',
    placement: {
      mode: 'corridor',
      corridorId: 'southwest-trail',
      distanceAlong: 17,
      lateralOffset: -2.6,
      yawMode: 'follow-road',
      yawOffset: 0,
      yOffset: 0.18,
    },
    interactionRadius: 3.2,
    priorityTier: 'standard',
    visualRecipe: {
      archetype: 'field-station',
      palette: 'extra-cobalt',
      accentMaterial: 'frosted-glass',
      propKit: 'field-kit',
      heroProp: 'wayfinder-arch',
      animationStyle: 'soft-orbit',
    },
    draftNotes: 'Reserved for extracurricular and community benches after the recruiter MVP ships.',
  },
];

export const WORKBENCH_LAYOUT: WorkbenchDefinition[] =
  applyPublishedWorkbenchRingLayout(RAW_WORKBENCH_LAYOUT);

export const PUBLISHED_WORKBENCH_CLEAR_ZONES = getPublishedWorkbenchClearZones(WORKBENCH_LAYOUT);
